<!--Basketball tables-->

```{r Libraries, message = FALSE, warning = FALSE, echo = FALSE}
# Load libraries
library(XML); library(tidyverse); library(plyr); library(rmarkdown); library(scales); library(knitr); library(shiny); library(htmltools); library(DT); library(ballr)
```

```{r Local options, echo = FALSE}
# Setting global knitr options for document
knitr::opts_chunk$set(out.width='50%', out.height='50%', fig.align = "center")
knitr::opts_chunk$set(message = FALSE, warning = FALSE) 
knitr::opts_chunk$set(cache = TRUE)
knitr::opts_chunk$set(results = 'hold')
```

<!--Start Document-->

## Salaries

This app scrapes salary data from [Hoopshype.com](www.hoopshype.com) and combines them into one single 
table that is sortable and filterable.


```{r List of NBA Teams, echo=FALSE}
# List of all NBA teams
teams <- c("atlanta_hawks", "brooklyn_nets", "boston_celtics", "charlotte_hornets", "chicago_bulls", "cleveland_cavaliers", "dallas_mavericks", "denver_nuggets", "detroit_pistons", "golden_state_warriors", "houston_rockets", "indiana_pacers", "los_angeles_clippers", "los_angeles_lakers", "memphis_grizzlies", "miami_heat", "milwaukee_bucks", "minnesota_timberwolves", "new_orleans_pelicans", "new_york_knicks", "oklahoma_city_thunder", "orlando_magic", "philadelphia_76ers", "phoenix_suns", "portland_trail_blazers", "sacramento_kings", "san_antonio_spurs", "toronto_raptors", "utah_jazz", "washington_wizards")
```

```{r Scraping salaries, echo=FALSE}
# Scrape all team salaries from hoopshype
generic_link <- "http://www.hoopshype.com/salaries/"
salaries_list <- as.list(NULL)
for(i in 1:length(teams)){
    link <- paste(generic_link, teams[i], sep = "")
    salaries_list[[i]] <- readHTMLTable(link, stringsAsFactors = FALSE)[[1]]
    salaries_list[[i]]$team <- teams[i]
}
names(salaries_list) <- teams
```

```{r Creating salary table, echo = FALSE}
# Combine dfs from list into one df
salaries_df <- bind_rows(salaries_list)

# Fill NAs
salaries_df[salaries_df == ""] <- "$0"

# Convert $ into numeric
numericDF <- as.data.frame(sapply(salaries_df, as.factor))
numericDF[,-c(1,8)] <- as.numeric(gsub("[$,]", "", as.matrix(numericDF[,-c(1,8)])))

currencyDF <- numericDF
currencyDF[,-c(1,8)] <- sapply(currencyDF[,-c(1,8)], dollar)
```

```{r Table of Salaries, echo = FALSE}
# Print datatable of all salaries
DT::datatable(currencyDF)
```

*****

## Stats

```{r Get Fantasy bball positions and stats}
# Get per game stats from ballr library
per_game_stats <- NBAPerGameStatistics(season = 2017)

# Condense the dataframe to eliminate multiple entries per player
condensed_per_game <- per_game_stats %>% 
    group_by(Player, Pos) %>%
    filter(Tm == "TOT" | n()==1)

```





*****

```{r Template, eval = FALSE, echo = FALSE}
atlanta_hawks <- readHTMLTable("http://hoopshype.com/salaries/atlanta_hawks", stringsAsFactors = FALSE)[[1]]
boston_celtics <- readHTMLTable("http://hoopshype.com/salaries/boston_celtics", stringsAsFactors = FALSE)[[1]]
```

